### PR TITLE
Create new-contributor.md

### PR DESCRIPTION
**Pull request by benhylau**
I am emailing this to @Shrinks99 and @ASoTNetworks to trial the onboard process.

### CODE REVIEW

**Comment by makeworld-the-better-one** [comment]
https://lists.hypha.coop/cgi-bin/mailman/listinfo/tomeshnet gives me an error "No such list tomeshnet".

**Comment by benhylau** [comment]
Ahhh I think there was a mixup. @ASoTNetworks I meant change the _display name_ of the list to Toronto Mesh not the actual list :)

**Comment by ASoTNetworks** [comment]
The list was changed to https://lists.hypha.coop/cgi-bin/mailman/listinfo/toronto_mesh as renaming it wasn't possible and only allows case changes in the name.

**Comment by benhylau** [comment]
Ahhh then can we change it back? I guess this means deleting it and creating a new list... sorry for the back and forth I didn't realize the restriction, but we should keep the list email `tomeshnet` because of #30

**Comment by ASoTNetworks** [comment]
I have removed `Toronto_Mesh` and added `tomeshnet` -> https://lists.hypha.coop/cgi-bin/mailman/listinfo/tomeshnet

**Pull request merged**
